### ISSUE TITLE
can't get modbus working on MacBook with Arduino UNO and Max6675K

### ISSUE THREAD

**Issue by niallmca** [lukeinator42/coffee-roaster#1]
**Modbus Error: readSingleRegister() Exception response@line 29640**

Hi Lukas,

I have exact same configuration as you:
Arduino UNO with Max6675K thermocouple on pins 2,3,4,5,6
Using your sketch, and the same Device, Port settings,
and the same Modbus RTU library.

I've confirmed the Max6675 returns the correct temp and it is cast (without any error/warning), and I can see both TX and RX lights flickering on UNO.  But, Artisan just shows Modbus communication error.

I've tried also with a Windows 7 PC, and I get the same result :(

For the Arduino sketch, I've tried compile/upload using the IDE  on the Mac and also Arduino Create (the web editor).

Any ideas?

**Comment by niallmca** [comment]
actually, I've noticed that the Arduino TX light never goes on.  Only RX.
So, the Arduino is receiving the Modbus messages but is never sending the temperature data.

`slave.poll( au16data, 16 );` doesn't seem to be working, but I don't know why.

The USB cable and driver should be ok because I am able to download the sketch, and I see both TX and RX lights working.


Any ideas/suggestions welcome.

Thanks.
Best regards,
Niall.

**Comment by niallmca** [comment]
ok, I got it working ...

I used this modified version of the ModbusRTU library.
https://github.com/pylonsoft/Modbus-Master-Slave-for-Arduino

Thanks!
Best regards,
Niall.

**Comment by lukeinator42** [comment]
@niallmca glad to hear you got it working!
