### ISSUE TITLE
Incorrect library link

### ISSUE THREAD

**Issue by per1234** [lukeinator42/coffee-roaster#3]
README.md says:
>and the [ModbusRTU](https://github.com/4-20ma/ModbusMaster) library

But that link points to the ModbusMaster library, not the ModbusRTU library. The ModbusMaster library does not contain a file named ModbusRtu.h, as required by the sketch:
https://github.com/lukeinator42/coffee-roaster/blob/201a892e2edc3ba088a35d4a0e7f936bebea227f/sketch/sketch.ino#L6
The ModbusMaster library doesn't appear to have ever had such a file. The Arduino Library Manager does not provide any libraries of that name and the couple with a similar name don't contain the required file. I did find this library:
https://github.com/smarmengol/Modbus-Master-Slave-for-Arduino
which contains a file of that name and the sketch compiles. Is that the library you are using?

**Comment by lukeinator42** [comment]
@per1234  Yup, that's the library, good catch! I had updated the medium blog post but looks like I forgot to fix the readme.
