### ISSUE TITLE
Modbus Communication Error

### ISSUE THREAD

**Issue by supriyadiatmi35** [lukeinator42/coffee-roaster#5]
Hello Sir,
Can you help me please?I already follow the instruction, but I get Modbus Communication Error.
TIA.

**Comment by haiduc32** [comment]
Same here...

**Comment by rollag16** [comment]
Same..too

**Comment by masfen** [comment]
same here

**Comment by tgterra** [comment]
Change MODBUS port configuration "parity" to N resolved the problem to me.

**Comment by abraham-romero-torres** [comment]
> Change MODBUS port configuration "parity" to N resolved the problem to me.

This also worked for me!

**Comment by alfredolsnc** [comment]
changing the MODBUS port config ''parity'' to N also solved the issue for me. But if it persists try checking things like baud rate and bits per second on your usb port  - they need to match. You can check the one of your usb port through device manager-ports-select your port-properties-port settings.

**Comment by lukeinator42** [comment]
see solution above
